APPLY_FIXES: none
VALIDATE_ALL_CODEBASE: true
SHOW_ELAPSED_TIME: true
PRINT_ALPACA: false
REPORT_OUTPUT_FOLDER: megalinter-reports
DISABLE_LINTERS:
  - REPOSITORY_TRIVY
  - REPOSITORY_GITLEAKS
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "(^|/)vendor/|(^|/)node_modules/|(^|/)artifacts/"

