APPLY_FIXES: none
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - BASH_SHELLCHECK
  - JSON_JSONLINT
  - YAML_YAMLLINT
SHOW_ELAPSED_TIME: true
PRINT_ALPACA: false
REPORT_OUTPUT_FOLDER: devsecops/reports/megalinter

